DROP TABLE LOGIN;

CREATE TABLE LOGIN(
	FNAME 		VARCHAR2(30),		
	LNAME 		VARCHAR2(30),		
	DOB 		DATE,		
	EMAIL 		VARCHAR2(50),		
	MOBILE_NO 	NUMBER(10),		
	GENDER 		VARCHAR2(7),		
	ADDRESS 	VARCHAR2(100),		
	CITY 		VARCHAR2(30),		
	PINCODE 	NUMBER(6),		
	STATE 		VARCHAR2(30),		
	COUNTRY 	VARCHAR2(30),		
	HOBBIES 	VARCHAR2(30),		
	COURSE 		VARCHAR2(7)		
);
