# Google java formatter workflow
name: Google Java Formatter

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-javadoc-formatting --replace"
          commitMessage: "Format - Google java formatter"